import "bulma/css/bulma.css";
import classNames from "classnames";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import { DarkModeSwitch } from "@/components/client/dark_mode_switch";
import { loadSourceData } from "@/utils/load_source_data";

import Styles from "./layout.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sourceData = await loadSourceData();
  const items = sourceData.identifiers.map((identifier) => {
    return (
      <li key={`menu-${identifier}`}>
        <Link href={`/layers/${identifier}`}>{identifier}</Link>
      </li>
    );
  });
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Styles.html}`}
      >
        <nav className="navbar is-primary">
          <div className="navbar-brand">
            <Link href="/" className="navbar-item title">
              Luciferous Public Layers
            </Link>
          </div>
          <div className="navbar-end">
            <div className="navbar-item">
              <DarkModeSwitch />
            </div>
          </div>
        </nav>
        <div className={classNames("columns", Styles.FullHeight)}>
          <div
            className={classNames(
              "column",
              "is-one-fifth",
              "pl-5",
              "pt-5",
              Styles.RightLine,
            )}
          >
            <aside className="menu">
              <ul className="menu-list">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/layers">Layers</Link>
                  <ul>{items}</ul>
                </li>
              </ul>
            </aside>
          </div>
          <div className="column">
            <div className="container pt-5 pb-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
